---
- name: "Create group for {{ amq_user }}"
  group: 
    name: "{{ amq_group }}"
    state: present
    
- name: "Create {{ amq_user }} as user"
  user: 
    name: "{{ amq_user }}"
    state: present
    shell: /bin/bash
    group: "{{ amq_group }}"
    create_home: "no"
    append: "no"

- name: "Verify activemq availability on the server"
  stat: 
    path: "{{ amq_install_dir }}/apache-activemq-{{ amq_version }}"
  register: activemq_avail
    
- name: "Download activemq"
  get_url:
    url: "{{ amq_url }}"
    dest: "/tmp/apache-activemq-{{ amq_version }}-bin.tar.gz"
    owner: "{{ amq_user }}"
    group: "{{ amq_group }}"
  when: not activemq_avail.stat.exists
    
- name: "Unarchive activemq tarball"
  unarchive:
    src: "/tmp/apache-activemq-{{ amq_version }}-bin.tar.gz"
    dest: "{{ amq_install_dir }}"
    owner: "{{ amq_user }}"
    group: "{{ amq_group }}"
    copy: no
  when: not activemq_avail.stat.exists
    
- name: "Create link"
  file: 
    src: "{{ amq_install_dir }}/apache-activemq-{{ amq_version }}"
    dest: "{{ amq_install_dir }}/activemq"
    state: link
    owner: "{{ amq_user }}"
    group: "{{ amq_group }}"
  when: not activemq_avail.stat.exists
    
- name: "Copy the activemq.xml config file"
  template:
    src: "activemq.xml.j2"
    dest: "{{ amq_install_dir }}/activemq/conf/activemq.xml"
    owner: "{{ amq_user }}"
    group: "{{ amq_group }}"
  become: yes
  
- name: "Copy the wrapper.conf config file"
  template:
    src: "/templates/wrapper.conf.j2"
    dest: "{{ amq_install_dir }}/activemq/bin/linux-x86-64/activemq"
    owner: "{{ amq_user }}"
    group: "{{ amq_group }}"
  become: yes
  
- name: "Copy the activemq credentials"
  copy:
    src: "/files/credentials.properties"
    dest: "{{ amq_install_dir }}/activemq/conf/"
    owner: "{{ amq_user }}"
    group: "{{ amq_group }}"
  become: yes
  
- name: "Copy the jetty realm file"
  copy:
    src: "/files/jetty-realm.properties"
    dest: "{{ amq_install_dir }}/activemq/conf/"
    owner: "{{ amq_user }}"
    group: "{{ amq_group }}"
  become: yes
  
- name: "Copy the init script file"
  copy: 
    src: "/files/activemq-service"
    dest: "{{ amq_install_dir }}/activemq/bin/linux-x86-64/activemq"
    owner: root
    group: root
  
- name: "Copy the activemq startup file"
  template:
    src: "activemq.j2"
    dest: "{{ amq_install_dir }}/activemq/bin/linux-x86-64/activemq"
    owner: "{{ amq_user }}"
    group: "{{ amq_group }}"
  become: "yes"

- name: "Copy init script file into init.d"
  copy:
    src: "{{ amq_install_dir }}/activemq/bin/linux-x86-64/activemq"
    dest: "/etc/init.d/activemq"
    owner: "root"
    group: "root"
    mode: 0755

- name: "Generate /etc/sysconfig/activemq Redhat"
  template:
    src: sysconfig_activemq.j2
    dest: /etc/sysconfig/activemq
    owner: root
    group: root
    mode: 0755
    
- name: "Copy the service file"
  template:
    src: "activemq.service.j2"
    dest: "/etc/systemd/system/activemq.service"
    owner: "root"
    group: "root"
    mode: 0755
  notify: Restart activeMQ service 
  become: yes
  
- name: "Change ActiveMQ folder permissions"
  file: 
    path: "{{ amq_install_dir }}/apache-activemq-{{ amq_version }}{{ item.directory }}"
    owner: "{{ amq_user }}"
    group: "{{ amq_group }}"
    mode: "{{ item.permissions }}"
    recurse: "yes"
  with_items:
    - { directory: "/", permissions: "0755"}
  notify: Start activeMQ service
  
- name: "Generate empty log file ..."
  file:
    path: "{{ amq_log_dir }}"
    state: touch
    mode: 0644
    owner: root
    group: root
    
- name: Start the Activemq service
  service:
    name: activemq
    state: started
    enabled: yes 