---
# activemq version
amq_version_major: "5"
amq_version_minor: "13"
amq_version_patch: "3"
amq_version: "{{ amq_version_major }}.{{ amq_version_minor }}.{{amq_version_patch }}"
amq_url: "http://archive.apache.org/dist/activemq/{{ amq_version }}/apache-activemq-{{amq_version }}-bin.tar.gz"
amq_openwire_transport_connector_uri: "tcp://0.0.0.0:61616?maximumConnections=1000&amp;wireFormat.maxFrameSize=104857600"

# amq vars
amq_user: activemq
amq_group:  activemq
amq_install_dir: /opt
amq_conf_dir: "{{ amq_install_dir }}/activemq/conf"
amq_run_dir: "{{ amq_install_dir }}/{{ amq_user }}"
#amq_home_dir:  /var/lib/activemq
amq_log_dir: /var/log/activemq
amq_env_vars:
  ACTIVEMQ_USER: "{{ amq_user }}"
  ACTIVEMQ_BASE: "/opt/{{ amq_user }}"
         
