---
# activemq version
amq_version_major: "5"
amq_version_minor: "13"
amq_version_patch: "3"
amq_version: "{{ amq_version_major }}.{{ amq_version_minor }}.{{amq_version_patch }}"
amq_url: "http://archive.apache.org/dist/activemq/{{ amq_version }}/apache-activemq-{{amq_version }}-bin.tar.gz"
java_path: "/opt/jdk1.8.0_202"
         
